version: '3.9'

services:
  # app:
  #   build: .    
  #   ports:
  #     - 8000:8000
  #   env_file: .env
  #   depends_on:
  #     - db  


  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5