CREATE TABLE USERS (
     ID         UUID PRIMARY KEY,
     LOGIN      TEXT UNIQUE NOT NULL,
     PASSWORD   TEXT NOT NULL,
     TOKEN      TEXT,
     CREATED_AT TIMESTAMPTZ DEFAULT now()
    );

CREATE TABLE DOCUMENTS (
    ID         UUID PRIMARY KEY,
    USER_ID    UUID REFERENCES USERS(ID),
    FILENAME   TEXT NOT NULL,
    PATH       TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
    );