 ALTER TABLE DOCUMENTS
 ADD COLUMN MIME  TEXT NOT NULL,      
 ADD COLUMN HAS_FILE    BOOLEAN NOT NULL,    
 ADD COLUMN IS_PUBLIC   BOOLEAN NOT NULL;   

CREATE INDEX ON DOCUMENTS (USER_ID);     
CREATE INDEX ON DOCUMENTS (CREATED_AT);  