ALTER TABLE DOCUMENTS
  ADD COLUMN JSON_DATA JSONB; 

CREATE TABLE DOCUMENT_GRANTS (
  DOC_ID  UUID REFERENCES DOCUMENTS(ID) ON DELETE CASCADE,
  LOGIN   TEXT NOT NULL,
  PRIMARY KEY (DOC_ID, LOGIN)
);

