ALTER TABLE DOCUMENTS
  ADD COLUMN JSON_DATA JSONB; 

CREATE TABLE DOCUMENT_GRANTS (
  DOC_ID    UUID REFERENCES DOCUMENTS(ID) ON DELETE CASCADE,
  USER_ID   UUID REFERENCES USERS(ID) ON DELETE CASCADE,
  PRIMARY KEY (DOC_ID, USER_ID)
);

INSERT INTO DOCUMENT_GRANTS VALUES(
  'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'
)

